### PR TITLE
Add options `formatOnBlur` and `reverse`

### PR DESCRIPTION
**Pull request by abduncan**
@danieltartarottisobrosa Daniel, I added two new options to support a scenario we need.  I've updated the README.md file with documentation for those options, index.html with examples.

I've run all tests and updated the dist version.  Let me know if I need to do anything else.

### CODE REVIEW

**Comment by abduncan** [comment]
Just realized this was a fork.

**Comment by danieltartarottisobrosa** [comment]
@abduncan, why did you close the pull request? I'd like to merge it.

**Comment by abduncan** [comment]
@danieltartarottisobrosa Hey sorry about that, I deleted the repo and created a fork of the original project and created a PR to it.  I can't figure out how to PR that code into this repo.

**Comment by danieltartarottisobrosa** [comment]
@abduncan  OK. No problem.

**Comment by abduncan** [comment]
@danieltartarottisobrosa Hey, just wanted to give you an, plentz merged the features I added into the base branch.  You can get them by pulling down.

**Comment by danieltartarottisobrosa** [comment]
Ok @abduncan, when I have some time I will pull your commits down. Thanks.

**Pull request closed without merging**
